// Generated by OpenSpec.
// @generated by OpenSpec. Do not edit.
// biome-ignore-all format: generated code.
// biome-ignore-all assist/source/organizeImports: generated code.

export type CommanderCommandOptionContract = {
	name: string;
	flag: string;
	valueType: string;
	required?: boolean;
	description?: string;
	defaultValue?: unknown;
	values?: string[];
};

export type CommanderCommandContract = {
	id: string;
	command: string;
	actionName: string;
	description?: string;
	options: CommanderCommandOptionContract[];
};

export type CommanderProgramContract = {
	id: string;
	unit: string;
	target: string;
	owner: string;
	providerSelection: string;
	factoryName: string;
	programName: string;
	description?: string;
	commands: CommanderCommandContract[];
};

export type CommanderProgramRecipeInput = {
	program: CommanderProgramContract;
};
