// Generated by OpenSpec.
// @generated by OpenSpec. Do not edit.
// biome-ignore-all format: generated code.
// biome-ignore-all assist/source/organizeImports: generated code.

import type { TextFileArtifactRecipe } from "@openspec/artifact-render-capability/types";
import type { TypeScriptSyntaxRenderInput } from "./typescript-dialect-types.generated";

export type TypeScriptSyntaxRenderAdapter = {
	render: (input: TypeScriptSyntaxRenderInput) => Promise<TextFileArtifactRecipe> | TextFileArtifactRecipe;
};

export function implementTypeScriptSyntaxRenderAdapter(
	adapter: TypeScriptSyntaxRenderAdapter,
): TypeScriptSyntaxRenderAdapter {
	return adapter;
}
