// Generated by OpenSpec.
// @generated by OpenSpec. Do not edit.
// biome-ignore-all format: generated code.
// biome-ignore-all assist/source/organizeImports: generated code.

export type SyntaxUnitContract = {
	nodeId?: string;
	id?: string;
	kind?: string;
	role?: string;
	subject?: string;
};

export type AssetContract = {
	nodeId?: string;
	id?: string;
	locator?: { kind?: string; path?: string };
	mediaType?: string;
	disposition?: "generated" | "scaffold";
	language?: string;
};

export type ProviderSelectionContract = {
	id?: string;
	request?: string;
	target?: string;
	role?: string;
	provider?: string;
	offering?: string;
	dialect?: string;
	adapter?: string;
	projectionKind?: string;
	params?: unknown;
};

export type TypeScriptIdentifierExpression = {
	kind: "identifier";
	name: string;
};

export type TypeScriptMemberExpression = {
	kind: "member";
	object: TypeScriptValueExpression;
	property: string;
};

export type TypeScriptElementAccessExpression = {
	kind: "elementAccess";
	object: TypeScriptValueExpression;
	element: TypeScriptValueExpression;
};

export type TypeScriptCallExpression = {
	kind: "call";
	callee: TypeScriptValueExpression;
	arguments?: TypeScriptValueExpression[];
};

export type TypeScriptNewExpression = {
	kind: "new";
	callee: TypeScriptValueExpression;
	arguments?: TypeScriptValueExpression[];
};

export type TypeScriptAwaitExpression = {
	kind: "await";
	value: TypeScriptValueExpression;
};

export type TypeScriptUnaryExpression = {
	kind: "unary";
	operator: string;
	value: TypeScriptValueExpression;
};

export type TypeScriptObjectPropertyExpression = {
	key: string;
	value: TypeScriptValueExpression;
};

export type TypeScriptObjectExpression = {
	kind: "object";
	properties: TypeScriptObjectPropertyExpression[];
};

export type TypeScriptArrayExpression = {
	kind: "array";
	items: TypeScriptValueExpression[];
};

export type TypeScriptLiteralExpression = {
	kind: "literal";
	value: string | number | boolean | null;
};

export type TypeScriptArrowFunctionExpression = {
	kind: "arrowFunction";
	async?: boolean;
	parameters?: TypeScriptFunctionParameter[];
	body: TypeScriptValueExpression | TypeScriptBlockStatement;
};

export type TypeScriptRawExpression = {
	kind: "raw";
	text: string;
};

export type TypeScriptValueExpression =
	| TypeScriptIdentifierExpression
	| TypeScriptMemberExpression
	| TypeScriptElementAccessExpression
	| TypeScriptCallExpression
	| TypeScriptNewExpression
	| TypeScriptAwaitExpression
	| TypeScriptUnaryExpression
	| TypeScriptObjectExpression
	| TypeScriptArrayExpression
	| TypeScriptLiteralExpression
	| TypeScriptArrowFunctionExpression
	| TypeScriptRawExpression;

export type TypeScriptKeywordTypeExpression = {
	kind: "keyword";
	name: string;
};

export type TypeScriptRefTypeExpression = {
	kind: "ref";
	name: string;
};

export type TypeScriptArrayTypeExpression = {
	kind: "array";
	item: TypeScriptTypeExpression;
};

export type TypeScriptObjectTypeProperty = {
	name: string;
	type: TypeScriptTypeExpression;
	optional?: boolean;
	readonly?: boolean;
	comment?: string;
};

export type TypeScriptObjectTypeExpression = {
	kind: "object";
	properties: TypeScriptObjectTypeProperty[];
};

export type TypeScriptRecordTypeExpression = {
	kind: "record";
	key: TypeScriptTypeExpression;
	value: TypeScriptTypeExpression;
};

export type TypeScriptUnionTypeExpression = {
	kind: "union";
	options: TypeScriptTypeExpression[];
};

export type TypeScriptIntersectionTypeExpression = {
	kind: "intersection";
	options: TypeScriptTypeExpression[];
};

export type TypeScriptLiteralTypeExpression = {
	kind: "literal";
	value: string | number | boolean | null;
};

export type TypeScriptPromiseTypeExpression = {
	kind: "promise";
	value: TypeScriptTypeExpression;
};

export type TypeScriptTypeQueryExpression = {
	kind: "typeQuery";
	expression: TypeScriptValueExpression;
};

export type TypeScriptTypeApplicationExpression = {
	kind: "typeApplication";
	base: TypeScriptTypeExpression;
	arguments: TypeScriptTypeExpression[];
};

export type TypeScriptRawTypeExpression = {
	kind: "raw";
	text: string;
};

export type TypeScriptFunctionTypeExpression = {
	kind: "function";
	parameters: TypeScriptFunctionParameter[];
	returnType: TypeScriptTypeExpression;
};

export type TypeScriptTypeExpression =
	| TypeScriptKeywordTypeExpression
	| TypeScriptRefTypeExpression
	| TypeScriptArrayTypeExpression
	| TypeScriptObjectTypeExpression
	| TypeScriptRecordTypeExpression
	| TypeScriptUnionTypeExpression
	| TypeScriptIntersectionTypeExpression
	| TypeScriptLiteralTypeExpression
	| TypeScriptPromiseTypeExpression
	| TypeScriptTypeQueryExpression
	| TypeScriptTypeApplicationExpression
	| TypeScriptFunctionTypeExpression
	| TypeScriptRawTypeExpression;

export type TypeScriptFunctionParameter = {
	name: string;
	type?: TypeScriptTypeExpression;
	optional?: boolean;
	rest?: boolean;
};

export type TypeScriptRawStatement = {
	kind: "raw";
	text: string;
};

export type TypeScriptConstStatement = {
	kind: "const";
	name: string;
	type?: TypeScriptTypeExpression;
	value: TypeScriptValueExpression;
};

export type TypeScriptExpressionStatement = {
	kind: "expression";
	expression: TypeScriptValueExpression;
};

export type TypeScriptReturnStatement = {
	kind: "return";
	value?: TypeScriptValueExpression;
};

export type TypeScriptThrowStatement = {
	kind: "throw";
	value: TypeScriptValueExpression;
};

export type TypeScriptBlockStatement = {
	kind: "block";
	statements: TypeScriptStatement[];
};

export type TypeScriptIfStatement = {
	kind: "if";
	condition: TypeScriptValueExpression;
	then: TypeScriptStatement[];
	else?: TypeScriptStatement[];
};

export type TypeScriptChainedCall = {
	method: string;
	arguments?: TypeScriptValueExpression[];
};

export type TypeScriptChainedCallStatement = {
	kind: "chainedCall";
	receiver: TypeScriptValueExpression;
	calls: TypeScriptChainedCall[];
};

export type TypeScriptStatement =
	| TypeScriptRawStatement
	| TypeScriptConstStatement
	| TypeScriptExpressionStatement
	| TypeScriptReturnStatement
	| TypeScriptThrowStatement
	| TypeScriptBlockStatement
	| TypeScriptIfStatement
	| TypeScriptChainedCallStatement;

export type TypeScriptImportBinding = {
	imported: string;
	local?: string;
};

export type TypeScriptImportFacetValue = {
	unit?: string;
	module: string;
	order?: number;
	named?: TypeScriptImportBinding[];
	default?: string;
	namespace?: string;
};

export type TypeScriptDeclarationFacetValue = {
	unit?: string;
	kind: string;
	name: string;
	role?: string;
	order?: number;
	exported?: boolean;
	comment?: string;
	value?: TypeScriptValueExpression;
	type?: TypeScriptTypeExpression;
	parameters?: TypeScriptFunctionParameter[];
	returnType?: TypeScriptTypeExpression;
	body?: TypeScriptStatement[];
};

export type TypeScriptImportFacetContract = {
	id: string;
	kind?: string;
	target?: string;
	unit?: string;
	value: TypeScriptImportFacetValue;
};

export type TypeScriptDeclarationFacetContract = {
	id: string;
	kind?: string;
	target?: string;
	unit?: string;
	value: TypeScriptDeclarationFacetValue;
};

export type TypeScriptRecipeInvocationFacetValue = {
	unit?: string;
	recipe: string;
	provider?: string;
	adapter?: string;
	providerSelectionRequest?: string;
	role?: string;
	order?: number;
	input?: unknown;
	inputModel?: string;
};

export type TypeScriptRecipeInvocationContract = {
	id: string;
	kind?: string;
	target?: string;
	unit?: string;
	value: TypeScriptRecipeInvocationFacetValue;
};

export type TypeScriptRecipeApplyInput = {
	invocation: TypeScriptRecipeInvocationContract;
	unit: unknown;
	asset: unknown;
};

export type TypeScriptRecipeApplyResult = {
	edits?: TypeScriptModuleEdit[];
	sourceText?: string;
	diagnostics?: unknown;
};

export type TypeScriptImportModuleEdit = {
	kind: "import";
	order?: number;
	module: string;
	named?: TypeScriptImportBinding[];
	default?: string;
	namespace?: string;
};

export type TypeScriptTypeAliasModuleEdit = {
	kind: "typeAlias";
	order?: number;
	name: string;
	exported?: boolean;
	type: TypeScriptTypeExpression;
};

export type TypeScriptConstModuleEdit = {
	kind: "const";
	order?: number;
	name: string;
	exported?: boolean;
	type?: TypeScriptTypeExpression;
	value: TypeScriptValueExpression;
};

export type TypeScriptFunctionModuleEdit = {
	kind: "function";
	order?: number;
	name: string;
	exported?: boolean;
	parameters?: TypeScriptFunctionParameter[];
	returnType?: TypeScriptTypeExpression;
	body: TypeScriptStatement[];
};

export type TypeScriptStatementModuleEdit = {
	kind: "statement";
	order?: number;
	statement: TypeScriptStatement;
};

export type TypeScriptFunctionBodyStatementModuleEdit = {
	kind: "functionBodyStatement";
	order?: number;
	functionName: string;
	statement: TypeScriptStatement;
};

export type TypeScriptRawModuleEdit = {
	kind: "raw";
	order?: number;
	text: string;
};

export type TypeScriptModuleEdit =
	| TypeScriptImportModuleEdit
	| TypeScriptTypeAliasModuleEdit
	| TypeScriptConstModuleEdit
	| TypeScriptFunctionModuleEdit
	| TypeScriptStatementModuleEdit
	| TypeScriptFunctionBodyStatementModuleEdit
	| TypeScriptRawModuleEdit;

export type TypeScriptSyntaxRenderInput = {
	unit: SyntaxUnitContract;
	asset: AssetContract;
	selections?: ProviderSelectionContract[];
	imports?: TypeScriptImportFacetContract[];
	declarations?: TypeScriptDeclarationFacetContract[];
	recipes?: TypeScriptRecipeInvocationContract[];
};
