// Generated by OpenSpec.
// @generated by OpenSpec. Do not edit.
// biome-ignore-all format: generated code.
// biome-ignore-all assist/source/organizeImports: generated code.

export type ProcedureInput = {
	description?: string;
	id: string;
	input?: Record<string, ProcedurePortInput>;
	kind?: string;
	links?: ProcedureLinkInput[];
	metadata?: unknown;
	name?: string;
	outcomes?: Record<string, ProcedureOutcomeInput>;
	output?: Record<string, ProcedurePortInput>;
	outputMapping?: unknown;
	owner: string;
	steps: ProcedureStepInput[];
};

export type ProcedureInvocationContract = {
	activity: string;
	activityNodeId: string;
	flow: string;
	id: string;
	inputMapping?: unknown;
	metadata?: unknown;
	method: string;
	outputMapping?: unknown;
	owner: string;
};

export type ProcedureInvocationsForFlowParams = {
	flow: string;
};

export type ProcedureInvocationsSelectorResult = ProcedureInvocationContract[];

export type ProcedureLinkInput = {
	condition?: unknown;
	description?: string;
	from: string;
	id: string;
	kind?: string;
	metadata?: unknown;
	sourcePort?: string;
	targetPort?: string;
	to: string;
};

export type ProcedureOutcomeInput = {
	kind?: string;
	metadata?: unknown;
	name: string;
	output?: unknown;
};

export type ProcedurePortInput = {
	description?: string;
	metadata?: unknown;
	model?: string;
	source?: unknown;
};

export type ProcedureSelectorNoParams = {};

export type ProcedureStepInput = {
	condition?: unknown;
	description?: string;
	id: string;
	input?: Record<string, ProcedurePortInput>;
	inputMapping?: unknown;
	kind?: string;
	metadata?: unknown;
	method: string;
	name?: string;
	outcomes?: Record<string, ProcedureOutcomeInput>;
	output?: Record<string, ProcedurePortInput>;
	outputMapping?: unknown;
};
