import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Node, Project, SyntaxKind } from "ts-morph";

type OperatorInfo = {
	inputType: string;
	outputType: string;
	aliases: string[];
};

const toOperatorType = (typeText: string | undefined): string => {
	if (typeText === undefined) {
		return "unknown";
	}
	return typeText.trim();
};

const mergeType = (left: string, right: string): string => {
	if (left === right) return left;
	return `${left} | ${right}`;
};

const extractAliases = (optionsArg: Node | undefined): string[] => {
	if (!optionsArg || !Node.isObjectLiteralExpression(optionsArg)) return [];
	const metadataProp = optionsArg.getProperty("metadata");
	if (!metadataProp || !Node.isPropertyAssignment(metadataProp)) return [];
	const metadataInit = metadataProp.getInitializer();
	if (!metadataInit || !Node.isObjectLiteralExpression(metadataInit)) return [];
	const aliasesProp = metadataInit.getProperty("aliases");
	if (!aliasesProp || !Node.isPropertyAssignment(aliasesProp)) return [];
	const aliasesInit = aliasesProp.getInitializer();
	if (!aliasesInit || !Node.isArrayLiteralExpression(aliasesInit)) return [];
	return aliasesInit
		.getElements()
		.filter(Node.isStringLiteral)
		.map((el) => el.getLiteralValue());
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const workspaceRoot = resolve(__dirname, "..", "..", "..", "..", "..");
const stdRoot = join(workspaceRoot, "packages", "expression", "expresso-std");
const sdkOutputPath = resolve(
	workspaceRoot,
	"packages",
	"expression",
	"expresso",
	"src",
	"operators.generated.ts",
);

const operatorFiles = readdirSync(stdRoot, { withFileTypes: true })
	.filter((entry) => entry.isDirectory())
	.map((entry) => join(stdRoot, entry.name, "src", "operators.ts"))
	.filter((filePath) => existsSync(filePath));

const project = new Project({
	useInMemoryFileSystem: false,
	skipAddingFilesFromTsConfig: true,
});

project.addSourceFilesAtPaths(operatorFiles);

const operators = new Map<string, OperatorInfo>();

for (const sourceFile of project.getSourceFiles()) {
	const calls = sourceFile.getDescendantsOfKind(SyntaxKind.CallExpression);
	for (const call of calls) {
		const callee = call.getExpression();
		if (!Node.isIdentifier(callee)) continue;
		const calleeName = callee.getText();
		if (
			calleeName !== "defineSyncOperator" &&
			calleeName !== "defineAsyncOperator"
		)
			continue;
		const [idArg, optionsArg] = call.getArguments();
		if (!idArg || !Node.isStringLiteral(idArg)) continue;
		const operatorId = idArg.getLiteralValue();
		const typeArgs = call.getTypeArguments();
		const inputType = toOperatorType(typeArgs[0]?.getText());
		const outputType = toOperatorType(typeArgs[1]?.getText());
		const aliases = extractAliases(optionsArg);
		const existing = operators.get(operatorId);
		if (existing) {
			operators.set(operatorId, {
				inputType: mergeType(existing.inputType, inputType),
				outputType: mergeType(existing.outputType, outputType),
				aliases: Array.from(new Set([...existing.aliases, ...aliases])),
			});
		} else {
			operators.set(operatorId, { inputType, outputType, aliases });
		}
	}
}

for (const [, info] of Array.from(operators.entries())) {
	for (const alias of info.aliases) {
		if (!operators.has(alias)) {
			operators.set(alias, {
				inputType: info.inputType,
				outputType: info.outputType,
				aliases: [],
			});
		}
	}
}

const sortedOperators = Array.from(operators.entries()).sort((a, b) =>
	a[0].localeCompare(b[0]),
);

const header =
	`// AUTO-GENERATED by expresso codegen. Do not edit.\n` +
	`/* eslint-disable @typescript-eslint/no-redundant-type-constituents */\n` +
	`import type { Rule } from '@gooi/expresso';\n\n`;

const inputMap = sortedOperators
	.map(([name, info]) => `  '${name}': ${info.inputType};`)
	.join("\n");

const outputMap = sortedOperators
	.map(([name, info]) => `  '${name}': ${info.outputType};`)
	.join("\n");

const contents =
	`${header}export type OperatorInputMap = {\n${inputMap}\n};\n\n` +
	`export type OperatorOutputMap = {\n${outputMap}\n};\n\n` +
	`export type OperatorName = keyof OperatorInputMap;\n`;

const outputDir = dirname(sdkOutputPath);
if (!existsSync(outputDir)) {
	mkdirSync(outputDir, { recursive: true });
}

writeFileSync(sdkOutputPath, contents, "utf8");
